#!/bin/sh

case "$1" in 
	dwm)	
		[ -f ~/.config/X11/xprofile ] && . ~/.config/X11/xprofile
		while :; do
	     		ssh-agent dwm || break
	     	done;;
	xfce) export XDG_SESSION_TYPE=x11
	      exec startxfce4;;
esac
